### ISSUE TITLE
Show zone wave requirements in the wiki

### ISSUE THREAD

**Issue by edbrannin** [MindustryGame/wiki-generator#1]
Twice recently (still in early levels) I've gone to the wiki to answer the question "Is there any benefit to staying longer in this level?" -- it seems like I can't safely learn the answer without asking on Discord or reading [Zones.java](https://github.com/Anuken/Mindustry/blob/master/core/src/io/anuke/mindustry/content/Zones.java).

Either of these would answer my question:
* Show "Needs Zone X, Wave Y" on downstream level pages
* Show "Highest-wave unlock" in the level-attributes table (but this might be a bit less clear if the other bullet isn't implemented)

**Comment by Anuken** [comment]
Closed with 6.0, as you need to capture sectors regardless.
