### ISSUE TITLE
Exotic Mod status effects show up in the statuses list

### ISSUE THREAD

**Issue by MEEPofFaith** [MindustryGame/wiki-generator#12]
![image](https://user-images.githubusercontent.com/54301439/158859542-32ab6462-6cd6-4a6e-82dd-c45149aac9b3.png)

**Comment by Anuken** [comment]
Known, was a bug in the status effect parser that was already fixed on Mindustry's end.

**Comment by MEEPofFaith** [comment]
~~"Already fixed in private branch" moment. (real)~~
