### ISSUE TITLE
Could you please display the ressources needed to create units?

### ISSUE THREAD

**Issue by schittli** [MindustryGame/wiki-generator#7]
Good evening

thank you very much for https://mindustrygame.github.io/wiki - it's great to have an automatically generated Doc for the game!

During the game, it is always a mystery what resources a factory needs to produce something. Of course, the game shows the resources:

![image](https://user-images.githubusercontent.com/8282673/113045555-48ac2180-919f-11eb-9b5e-2091298f70e4.png)

But it is a tedious puzzle every time and a comparison of possible icons _("We search an icon that has a slightly darker viollet and the element is shown rather vertically")_ to find out which resource is represented. 

But because we can see the unit name (Mono in this case), it would be great if we could see the required resources in the wiki; unfortunately they are not mentioned:

https://mindustrygame.github.io/wiki/units/20-mono/

Thanks a lot!, kind regards,
Thomas

**Comment by Falling10fruit** [comment]
Yes, I would also like to see what it takes to build a T1 support naval.

**Comment by Anuken** [comment]
Will be available next release/update, as this is now listed in-game.
